name := "L4"
version := "1.0"
scalaVersion := "2.12.8"
libraryDependencies += "org.scala-lang.modules" %% "scala-parser-combinators" % "1.1.2"
libraryDependencies += "org.scalatest" %% "scalatest" % "3.0.5" % "test"
